apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pricelist-config
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: pricelist
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps/templates/pricelist-config
    repoURL: https://github.com/gulec2000/gitops-demo-cl
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
