apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pricelist-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps/apps
    repoURL: https://github.com/gulec2000/gitops-demo-cl
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
