apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bubble-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: bubble
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/apps/bubble/overlays/bubble
    repoURL: https://github.com/gulec2000/gitops-demo-cl
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
